// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Registration_server_project.Entities;

public partial class Branch
{
    public int? PlantId { get; set; }

    public int BranchId { get; set; }

    public string BranchName { get; set; }

    public string BranchAddress { get; set; }

    public virtual Plant Plant { get; set; }
}