// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Registration_server_project.Entities;

public partial class Plant
{
    public int PlantId { get; set; }

    public string PlantName { get; set; }

    public string PlantAddress { get; set; }

    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();
}