// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Registration_server_project.Entities;

public partial class RegistrationDetail
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string City { get; set; }

    public string Password { get; set; }

    public virtual ICollection<LoginDetail> LoginDetails { get; set; } = new List<LoginDetail>();
}